polidat/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/webhooks/:source', to: 'webhooks#create'
  root 'static_pages#root'

  resource :dashboard
  resources :accounts
  resources :products
  resource :store
  resources :storefronts
  get 'storefronts/:id', to: 'storefronts#show'
  post 'storefronts/:id/checkout', to: 'storefronts#checkout'
  get 'storefronts/:id/checkout/:session/confirmation', to: 'storefronts#confirmation'
end

polidat/app/models/store.rb
class Store < ApplicationRecord
    belongs_to :user
    has_many :products, through: :user

    def self.find_by_request(request)
      puts "Finding by request"
  
      where(domain: request.domain)
        .or(where(subdomain: request.subdomain))
        .first
    end
end

polidat/app/controllers/stores_controller.rb
class StoresController < ApplicationController

    layout 'authorized'

    before_action :authenticate_user!

    def show
        @store = current_user.store
    end

    def edit
        @store = current_user.store
    end

    private

    def store_params
        params.require(:store).permit(
            :domain,
            :subdomain
        )
    end

end

polidat/app/helpers/stores_helper.rb
module StoresHelper
end

polidat/app/views/stores/show.html.erb
<%= content_for :page_title do %>
Store
<% end %>

<div class="bg-white shadow overflow-hidden sm:rounded-lg mt-4">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900">Store information</h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">
      <%= link_to "edit", edit_store_path, class: "underline" %>
    </p>
  </div>

  <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
    <dl class="sm:divide-y sm:divide-gray-200">

      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Name</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @store.name %></dd> 
      </div> 

      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">View</dt>
 
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">

        <a href="<%= storefronts_url + '/' + @store.id.to_s %>"><%= storefronts_url + '/' + @store.id.to_s %></a>

        </dd> 

      </div>

      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <dt class="text-sm font-medium text-gray-500">Subdomain</dt>
          <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @store.subdomain %></dd> 
      </div> 

    </dl>
  </div>
</div>